import type { Metadata } from "next";
import RandomDishes from "./components/RandomDishes";
import HomePage from "./components/HomePage";

export const metadata: Metadata = {
  title: "Alpha Bites",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function Home() {
  return (
    <>
      <HomePage />
      <RandomDishes />
    </>
  );
}
