import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons:{
    icon:'/logo.png'
  }
};

export default async function Home() {
  return (
    <>
      <>
        <div>Hello</div>
      </>
    </>
  );
}
