import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function Home() { 
  return(
    <>
    <h1>Welcome</h1>
    </>
  )
}